//IMPORTS / REQUIRES
const express = require('express');
const bodyParser = require('body-parser');
const axios = require('axios');

//VARIABLES
const app = express();
const port = 3100;

//TOP LEVEL MIDDLEWARE
app.use(bodyParser.json());

//ENDPOINTS
app.get('/api/people', (req, res) => {
  var peoplePageUrl = 'https://swapi.co/api/people';
  var peopleData = [];
  function swapiPeople() {
    axios.get(peoplePageUrl).then(response => {
      for(let i = 0 ; i < response.data.results.length ; i++) {
        peopleData.push(response.data.results[i])
      }
      if (response.data.next) {
        peoplePageUrl = response.data.next
        swapiPeople();
      }
      else {
        if (req.query.sortBy === 'name') {
          peopleData.sort((a,b) => (a.name > b.name) ? 1 : ((a.name < b.name) ? -1 : 0));
          res.status(200).send(peopleData)
        }
        else if (req.query.sortBy === 'height') {
          peopleData.sort((a,b) => a.height - b.height);
          res.status(200).send(peopleData)
        }
        else if (req.query.sortBy === 'mass') {
          peopleData.sort((a,b) => a.mass - b.mass);
          res.status(200).send(peopleData)
        }
        else {
          res.status(200).send(peopleData)
        }
      }
    }).catch( error => {
      res.status(404).send(error);
    })
  }
  swapiPeople();
})

app.get('/api/planets', (req, res) => {
  var planetsPageUrl = 'https://swapi.co/api/planets';
  var planetsData = [];
  // var updatedPlanetsData = [];
  function swapiPlanets() {
    axios.get(planetsPageUrl).then(response => {
      response.data.results.forEach( planet => {
        if (!planet.residents[0]) {
          planetsData.push(planet);
        }
        else {
          let residentUrls = [];
          planet.residents.forEach( residentUrl => {
            residentUrls.push(axios.get(residentUrl))
          });
          axios.all(residentUrls).then( residentsResponse => {
            for (let j = 0 ; j < residentsResponse.length ; j++) {
              planet.residents[j] = 'bob';
            }
            // console.log('residentsResponse length', residentsResponse.length);
          })
          planetsData.push(planet);
        }
      })
      if (response.data.next) {
        planetsPageUrl = response.data.next
        swapiPlanets();
      }
      else {
        res.status(200).send(planetsData)
      }
    }).catch( error => {
      res.status(404).send(error);
    })
  }
  swapiPlanets();
})

//LISTEN
app.listen(port, () => console.log(`listening on port ${port}!`));

// response from axios.all [ { status: 200,
//   statusText: 'OK',
//   headers: 
//    { date: 'Tue, 19 Feb 2019 10:29:29 GMT',
//      'content-type': 'application/json',
//      'transfer-encoding': 'chunked',
//      connection: 'close',
//      'set-cookie': [Object],
//      allow: 'GET, HEAD, OPTIONS',
//      vary: 'Accept, Cookie',
//      etag: '"c1bf3d69ac26afa100ae6665efd1d951"',
//      'x-frame-options': 'SAMEORIGIN',
//      via: '1.1 vegur',
//      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
//      server: 'cloudflare',
//      'cf-ray': '4ab80d7a6b15a08e-SLC' },
//   config: 
//    { adapter: [Function: httpAdapter],
//      transformRequest: [Object],
//      transformResponse: [Object],
//      timeout: 0,
//      xsrfCookieName: 'XSRF-TOKEN',
//      xsrfHeaderName: 'X-XSRF-TOKEN',
//      maxContentLength: -1,
//      validateStatus: [Function: validateStatus],
//      headers: [Object],
//      method: 'get',
//      url: 'https://swapi.co/api/people/82/',
//      data: undefined },
//   request: 
//    ClientRequest {
//      domain: null,
//      _events: [Object],
//      _eventsCount: 6,
//      _maxListeners: undefined,
//      output: [],
//      outputEncodings: [],
//      outputCallbacks: [],
//      outputSize: 0,
//      writable: true,
//      _last: true,
//      upgrading: false,
//      chunkedEncoding: false,
//      shouldKeepAlive: false,
//      useChunkedEncodingByDefault: false,
//      sendDate: false,
//      _removedHeader: {},
//      _contentLength: 0,
//      _hasBody: true,
//      _trailer: '',
//      finished: true,
//      _headerSent: true,
//      socket: [Object],
//      connection: [Object],
//      _header: 'GET /api/people/82/ HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: swapi.co\r\nConnection: close\r\n\r\n',
//      _headers: [Object],
//      _headerNames: [Object],
//      _onPendingData: null,
//      agent: [Object],
//      socketPath: undefined,
//      timeout: undefined,
//      method: 'GET',
//      path: '/api/people/82/',
//      _ended: true,
//      _redirectable: [Object],
//      parser: null,
//      res: [Object] },
//   data: 
//    { name: 'Sly Moore',
//      height: '178',
//      mass: '48',
//      hair_color: 'none',
//      skin_color: 'pale',
//      eye_color: 'white',
//      birth_year: 'unknown',
//      gender: 'female',
//      homeworld: 'https://swapi.co/api/planets/60/',
//      films: [Object],
//      species: [],
//      vehicles: [],
//      starships: [],
//      created: '2014-12-20T20:18:37.619000Z',
//      edited: '2014-12-20T21:17:50.496000Z',
//      url: 'https://swapi.co/api/people/82/' } } ]



     
// response from axios.all [ { status: 200,
//   statusText: 'OK',
//   headers: 
//    { date: 'Tue, 19 Feb 2019 10:29:30 GMT',
//      'content-type': 'application/json',
//      'transfer-encoding': 'chunked',
//      connection: 'close',
//      'set-cookie': [Object],
//      allow: 'GET, HEAD, OPTIONS',
//      vary: 'Accept, Cookie',
//      etag: '"66762737e5903ee3c226eb9c846e3bbb"',
//      'x-frame-options': 'SAMEORIGIN',
//      via: '1.1 vegur',
//      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
//      server: 'cloudflare',
//      'cf-ray': '4ab80d7a6d55a058-SLC' },
//   config: 
//    { adapter: [Function: httpAdapter],
//      transformRequest: [Object],
//      transformResponse: [Object],
//      timeout: 0,
//      xsrfCookieName: 'XSRF-TOKEN',
//      xsrfHeaderName: 'X-XSRF-TOKEN',
//      maxContentLength: -1,
//      validateStatus: [Function: validateStatus],
//      headers: [Object],
//      method: 'get',
//      url: 'https://swapi.co/api/people/77/',
//      data: undefined },
//   request: 
//    ClientRequest {
//      domain: null,
//      _events: [Object],
//      _eventsCount: 6,
//      _maxListeners: undefined,
//      output: [],
//      outputEncodings: [],
//      outputCallbacks: [],
//      outputSize: 0,
//      writable: true,
//      _last: true,
//      upgrading: false,
//      chunkedEncoding: false,
//      shouldKeepAlive: false,
//      useChunkedEncodingByDefault: false,
//      sendDate: false,
//      _removedHeader: {},
//      _contentLength: 0,
//      _hasBody: true,
//      _trailer: '',
//      finished: true,
//      _headerSent: true,
//      socket: [Object],
//      connection: [Object],
//      _header: 'GET /api/people/77/ HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: swapi.co\r\nConnection: close\r\n\r\n',
//      _headers: [Object],
//      _headerNames: [Object],
//      _onPendingData: null,
//      agent: [Object],
//      socketPath: undefined,
//      timeout: undefined,
//      method: 'GET',
//      path: '/api/people/77/',
//      _ended: true,
//      _redirectable: [Object],
//      parser: null,
//      res: [Object] },
//   data: 
//    { name: 'San Hill',
//      height: '191',
//      mass: 'unknown',
//      hair_color: 'none',
//      skin_color: 'grey',
//      eye_color: 'gold',
//      birth_year: 'unknown',
//      gender: 'male',
//      homeworld: 'https://swapi.co/api/planets/57/',
//      films: [Object],
//      species: [Object],
//      vehicles: [],
//      starships: [],
//      created: '2014-12-20T17:58:17.049000Z',
//      edited: '2014-12-20T21:17:50.484000Z',
//      url: 'https://swapi.co/api/people/77/' } } ]





// response from axios.all 
// [ { status: 200,
//   statusText: 'OK',
//   headers: 
//    { date: 'Tue, 19 Feb 2019 10:29:30 GMT',
//      'content-type': 'application/json',
//      'transfer-encoding': 'chunked',
//      connection: 'close',
//      'set-cookie': [Object],
//      allow: 'GET, HEAD, OPTIONS',
//      vary: 'Accept, Cookie',
//      etag: '"145c70f4eca80b4752674d42e5bf1bcf"',
//      'x-frame-options': 'SAMEORIGIN',
//      via: '1.1 vegur',
//      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
//      server: 'cloudflare',
//      'cf-ray': '4ab80d7a6c48a064-SLC' },
//   config: 
//    { adapter: [Function: httpAdapter],
//      transformRequest: [Object],
//      transformResponse: [Object],
//      timeout: 0,
//      xsrfCookieName: 'XSRF-TOKEN',
//      xsrfHeaderName: 'X-XSRF-TOKEN',
//      maxContentLength: -1,
//      validateStatus: [Function: validateStatus],
//      headers: [Object],
//      method: 'get',
//      url: 'https://swapi.co/api/people/1/',
//      data: undefined },
//   request: 
//    ClientRequest {
//      domain: null,
//      _events: [Object],
//      _eventsCount: 6,
//      _maxListeners: undefined,
//      output: [],
//      outputEncodings: [],
//      outputCallbacks: [],
//      outputSize: 0,
//      writable: true,
//      _last: true,
//      upgrading: false,
//      chunkedEncoding: false,
//      shouldKeepAlive: false,
//      useChunkedEncodingByDefault: false,
//      sendDate: false,
//      _removedHeader: {},
//      _contentLength: 0,
//      _hasBody: true,
//      _trailer: '',
//      finished: true,
//      _headerSent: true,
//      socket: [Object],
//      connection: [Object],
//      _header: 'GET /api/people/1/ HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: swapi.co\r\nConnection: close\r\n\r\n',
//      _headers: [Object],
//      _headerNames: [Object],
//      _onPendingData: null,
//      agent: [Object],
//      socketPath: undefined,
//      timeout: undefined,
//      method: 'GET',
//      path: '/api/people/1/',
//      _ended: true,
//      _redirectable: [Object],
//      parser: null,
//      res: [Object] },
//   data: 
//    { name: 'Luke Skywalker',
//      height: '172',
//      mass: '77',
//      hair_color: 'blond',
//      skin_color: 'fair',
//      eye_color: 'blue',
//      birth_year: '19BBY',
//      gender: 'male',
//      homeworld: 'https://swapi.co/api/planets/1/',
//      films: [Object],
//      species: [Object],
//      vehicles: [Object],
//      starships: [Object],
//      created: '2014-12-09T13:50:51.644000Z',
//      edited: '2014-12-20T21:17:56.891000Z',
//      url: 'https://swapi.co/api/people/1/' } },
// { status: 200,
//   statusText: 'OK',
//   headers: 
//    { date: 'Tue, 19 Feb 2019 10:29:29 GMT',
//      'content-type': 'application/json',
//      'transfer-encoding': 'chunked',
//      connection: 'close',
//      'set-cookie': [Object],
//      allow: 'GET, HEAD, OPTIONS',
//      vary: 'Accept, Cookie',
//      etag: '"3a58f420395ff0deed943e331d3bf74b"',
//      'x-frame-options': 'SAMEORIGIN',
//      via: '1.1 vegur',
//      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
//      server: 'cloudflare',
//      'cf-ray': '4ab80d7a6b45a088-SLC' },
//   config: 
//    { adapter: [Function: httpAdapter],
//      transformRequest: [Object],
//      transformResponse: [Object],
//      timeout: 0,
//      xsrfCookieName: 'XSRF-TOKEN',
//      xsrfHeaderName: 'X-XSRF-TOKEN',
//      maxContentLength: -1,
//      validateStatus: [Function: validateStatus],
//      headers: [Object],
//      method: 'get',
//      url: 'https://swapi.co/api/people/2/',
//      data: undefined },
//   request: 
//    ClientRequest {
//      domain: null,
//      _events: [Object],
//      _eventsCount: 6,
//      _maxListeners: undefined,
//      output: [],
//      outputEncodings: [],
//      outputCallbacks: [],
//      outputSize: 0,
//      writable: true,
//      _last: true,
//      upgrading: false,
//      chunkedEncoding: false,
//      shouldKeepAlive: false,
//      useChunkedEncodingByDefault: false,
//      sendDate: false,
//      _removedHeader: {},
//      _contentLength: 0,
//      _hasBody: true,
//      _trailer: '',
//      finished: true,
//      _headerSent: true,
//      socket: [Object],
//      connection: [Object],
//      _header: 'GET /api/people/2/ HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: swapi.co\r\nConnection: close\r\n\r\n',
//      _headers: [Object],
//      _headerNames: [Object],
//      _onPendingData: null,
//      agent: [Object],
//      socketPath: undefined,
//      timeout: undefined,
//      method: 'GET',
//      path: '/api/people/2/',
//      _ended: true,
//      _redirectable: [Object],
//      parser: null,
//      res: [Object] },
//   data: 
//    { name: 'C-3PO',
//      height: '167',
//      mass: '75',
//      hair_color: 'n/a',
//      skin_color: 'gold',
//      eye_color: 'yellow',
//      birth_year: '112BBY',
//      gender: 'n/a',
//      homeworld: 'https://swapi.co/api/planets/1/',
//      films: [Object],
//      species: [Object],
//      vehicles: [],
//      starships: [],
//      created: '2014-12-10T15:10:51.357000Z',
//      edited: '2014-12-20T21:17:50.309000Z',
//      url: 'https://swapi.co/api/people/2/' } },
// { status: 200,
//   statusText: 'OK',
//   headers: 
//    { date: 'Tue, 19 Feb 2019 10:29:29 GMT',
//      'content-type': 'application/json',
//      'transfer-encoding': 'chunked',
//      connection: 'close',
//      'set-cookie': [Object],
//      allow: 'GET, HEAD, OPTIONS',
//      vary: 'Accept, Cookie',
//      etag: '"8bfe31db65334ba71a5294d01382d3fe"',
//      'x-frame-options': 'SAMEORIGIN',
//      via: '1.1 vegur',
//      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
//      server: 'cloudflare',
//      'cf-ray': '4ab80d7a6c59a07c-SLC' },
//   config: 
//    { adapter: [Function: httpAdapter],
//      transformRequest: [Object],
//      transformResponse: [Object],
//      timeout: 0,
//      xsrfCookieName: 'XSRF-TOKEN',
//      xsrfHeaderName: 'X-XSRF-TOKEN',
//      maxContentLength: -1,
//      validateStatus: [Function: validateStatus],
//      headers: [Object],
//      method: 'get',
//      url: 'https://swapi.co/api/people/4/',
//      data: undefined },
//   request: 
//    ClientRequest {
//      domain: null,
//      _events: [Object],
//      _eventsCount: 6,
//      _maxListeners: undefined,
//      output: [],
//      outputEncodings: [],
//      outputCallbacks: [],
//      outputSize: 0,
//      writable: true,
//      _last: true,
//      upgrading: false,
//      chunkedEncoding: false,
//      shouldKeepAlive: false,
//      useChunkedEncodingByDefault: false,
//      sendDate: false,
//      _removedHeader: {},
//      _contentLength: 0,
//      _hasBody: true,
//      _trailer: '',
//      finished: true,
//      _headerSent: true,
//      socket: [Object],
//      connection: [Object],
//      _header: 'GET /api/people/4/ HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: swapi.co\r\nConnection: close\r\n\r\n',
//      _headers: [Object],
//      _headerNames: [Object],
//      _onPendingData: null,
//      agent: [Object],
//      socketPath: undefined,
//      timeout: undefined,
//      method: 'GET',
//      path: '/api/people/4/',
//      _ended: true,
//      _redirectable: [Object],
//      parser: null,
//      res: [Object] },
//   data: 
//    { name: 'Darth Vader',
//      height: '202',
//      mass: '136',
//      hair_color: 'none',
//      skin_color: 'white',
//      eye_color: 'yellow',
//      birth_year: '41.9BBY',
//      gender: 'male',
//      homeworld: 'https://swapi.co/api/planets/1/',
//      films: [Object],
//      species: [Object],
//      vehicles: [],
//      starships: [Object],
//      created: '2014-12-10T15:18:20.704000Z',
//      edited: '2014-12-20T21:17:50.313000Z',
//      url: 'https://swapi.co/api/people/4/' } },
// { status: 200,
//   statusText: 'OK',
//   headers: 
//    { date: 'Tue, 19 Feb 2019 10:29:29 GMT',
//      'content-type': 'application/json',
//      'transfer-encoding': 'chunked',
//      connection: 'close',
//      'set-cookie': [Object],
//      allow: 'GET, HEAD, OPTIONS',
//      vary: 'Accept, Cookie',
//      etag: '"f04efbcf4eec6538821956db3d14cd99"',
//      'x-frame-options': 'SAMEORIGIN',
//      via: '1.1 vegur',
//      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
//      server: 'cloudflare',
//      'cf-ray': '4ab80d7a6e1fa03a-SLC' },
//   config: 
//    { adapter: [Function: httpAdapter],
//      transformRequest: [Object],
//      transformResponse: [Object],
//      timeout: 0,
//      xsrfCookieName: 'XSRF-TOKEN',
//      xsrfHeaderName: 'X-XSRF-TOKEN',
//      maxContentLength: -1,
//      validateStatus: [Function: validateStatus],
//      headers: [Object],
//      method: 'get',
//      url: 'https://swapi.co/api/people/6/',
//      data: undefined },
//   request: 
//    ClientRequest {
//      domain: null,
//      _events: [Object],
//      _eventsCount: 6,
//      _maxListeners: undefined,
//      output: [],
//      outputEncodings: [],
//      outputCallbacks: [],
//      outputSize: 0,
//      writable: true,
//      _last: true,
//      upgrading: false,
//      chunkedEncoding: false,
//      shouldKeepAlive: false,
//      useChunkedEncodingByDefault: false,
//      sendDate: false,
//      _removedHeader: {},
//      _contentLength: 0,
//      _hasBody: true,
//      _trailer: '',
//      finished: true,
//      _headerSent: true,
//      socket: [Object],
//      connection: [Object],
//      _header: 'GET /api/people/6/ HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: swapi.co\r\nConnection: close\r\n\r\n',
//      _headers: [Object],
//      _headerNames: [Object],
//      _onPendingData: null,
//      agent: [Object],
//      socketPath: undefined,
//      timeout: undefined,
//      method: 'GET',
//      path: '/api/people/6/',
//      _ended: true,
//      _redirectable: [Object],
//      parser: null,
//      res: [Object] },
//   data: 
//    { name: 'Owen Lars',
//      height: '178',
//      mass: '120',
//      hair_color: 'brown, grey',
//      skin_color: 'light',
//      eye_color: 'blue',
//      birth_year: '52BBY',
//      gender: 'male',
//      homeworld: 'https://swapi.co/api/planets/1/',
//      films: [Object],
//      species: [Object],
//      vehicles: [],
//      starships: [],
//      created: '2014-12-10T15:52:14.024000Z',
//      edited: '2014-12-20T21:17:50.317000Z',
//      url: 'https://swapi.co/api/people/6/' } },
// { status: 200,
//   statusText: 'OK',
//   headers: 
//    { date: 'Tue, 19 Feb 2019 10:29:29 GMT',
//      'content-type': 'application/json',
//      'transfer-encoding': 'chunked',
//      connection: 'close',
//      'set-cookie': [Object],
//      allow: 'GET, HEAD, OPTIONS',
//      vary: 'Accept, Cookie',
//      etag: '"16bdc0c7e9e33057e40645d60d15ad5c"',
//      'x-frame-options': 'SAMEORIGIN',
//      via: '1.1 vegur',
//      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
//      server: 'cloudflare',
//      'cf-ray': '4ab80d7a6c17a02e-SLC' },
//   config: 
//    { adapter: [Function: httpAdapter],
//      transformRequest: [Object],
//      transformResponse: [Object],
//      timeout: 0,
//      xsrfCookieName: 'XSRF-TOKEN',
//      xsrfHeaderName: 'X-XSRF-TOKEN',
//      maxContentLength: -1,
//      validateStatus: [Function: validateStatus],
//      headers: [Object],
//      method: 'get',
//      url: 'https://swapi.co/api/people/7/',
//      data: undefined },
//   request: 
//    ClientRequest {
//      domain: null,
//      _events: [Object],
//      _eventsCount: 6,
//      _maxListeners: undefined,
//      output: [],
//      outputEncodings: [],
//      outputCallbacks: [],
//      outputSize: 0,
//      writable: true,
//      _last: true,
//      upgrading: false,
//      chunkedEncoding: false,
//      shouldKeepAlive: false,
//      useChunkedEncodingByDefault: false,
//      sendDate: false,
//      _removedHeader: {},
//      _contentLength: 0,
//      _hasBody: true,
//      _trailer: '',
//      finished: true,
//      _headerSent: true,
//      socket: [Object],
//      connection: [Object],
//      _header: 'GET /api/people/7/ HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: swapi.co\r\nConnection: close\r\n\r\n',
//      _headers: [Object],
//      _headerNames: [Object],
//      _onPendingData: null,
//      agent: [Object],
//      socketPath: undefined,
//      timeout: undefined,
//      method: 'GET',
//      path: '/api/people/7/',
//      _ended: true,
//      _redirectable: [Object],
//      parser: null,
//      res: [Object] },
//   data: 
//    { name: 'Beru Whitesun lars',
//      height: '165',
//      mass: '75',
//      hair_color: 'brown',
//      skin_color: 'light',
//      eye_color: 'blue',
//      birth_year: '47BBY',
//      gender: 'female',
//      homeworld: 'https://swapi.co/api/planets/1/',
//      films: [Object],
//      species: [Object],
//      vehicles: [],
//      starships: [],
//      created: '2014-12-10T15:53:41.121000Z',
//      edited: '2014-12-20T21:17:50.319000Z',
//      url: 'https://swapi.co/api/people/7/' } },
// { status: 200,
//   statusText: 'OK',
//   headers: 
//    { date: 'Tue, 19 Feb 2019 10:29:30 GMT',
//      'content-type': 'application/json',
//      'transfer-encoding': 'chunked',
//      connection: 'close',
//      'set-cookie': [Object],
//      allow: 'GET, HEAD, OPTIONS',
//      vary: 'Accept, Cookie',
//      etag: '"da0bf4dd1a6f677f26ce731cc59e068d"',
//      'x-frame-options': 'SAMEORIGIN',
//      via: '1.1 vegur',
//      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
//      server: 'cloudflare',
//      'cf-ray': '4ab80d7a6849a04c-SLC' },
//   config: 
//    { adapter: [Function: httpAdapter],
//      transformRequest: [Object],
//      transformResponse: [Object],
//      timeout: 0,
//      xsrfCookieName: 'XSRF-TOKEN',
//      xsrfHeaderName: 'X-XSRF-TOKEN',
//      maxContentLength: -1,
//      validateStatus: [Function: validateStatus],
//      headers: [Object],
//      method: 'get',
//      url: 'https://swapi.co/api/people/8/',
//      data: undefined },
//   request: 
//    ClientRequest {
//      domain: null,
//      _events: [Object],
//      _eventsCount: 6,
//      _maxListeners: undefined,
//      output: [],
//      outputEncodings: [],
//      outputCallbacks: [],
//      outputSize: 0,
//      writable: true,
//      _last: true,
//      upgrading: false,
//      chunkedEncoding: false,
//      shouldKeepAlive: false,
//      useChunkedEncodingByDefault: false,
//      sendDate: false,
//      _removedHeader: {},
//      _contentLength: 0,
//      _hasBody: true,
//      _trailer: '',
//      finished: true,
//      _headerSent: true,
//      socket: [Object],
//      connection: [Object],
//      _header: 'GET /api/people/8/ HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: swapi.co\r\nConnection: close\r\n\r\n',
//      _headers: [Object],
//      _headerNames: [Object],
//      _onPendingData: null,
//      agent: [Object],
//      socketPath: undefined,
//      timeout: undefined,
//      method: 'GET',
//      path: '/api/people/8/',
//      _ended: true,
//      _redirectable: [Object],
//      parser: null,
//      res: [Object] },
//   data: 
//    { name: 'R5-D4',
//      height: '97',
//      mass: '32',
//      hair_color: 'n/a',
//      skin_color: 'white, red',
//      eye_color: 'red',
//      birth_year: 'unknown',
//      gender: 'n/a',
//      homeworld: 'https://swapi.co/api/planets/1/',
//      films: [Object],
//      species: [Object],
//      vehicles: [],
//      starships: [],
//      created: '2014-12-10T15:57:50.959000Z',
//      edited: '2014-12-20T21:17:50.321000Z',
//      url: 'https://swapi.co/api/people/8/' } },
// { status: 200,
//   statusText: 'OK',
//   headers: 
//    { date: 'Tue, 19 Feb 2019 10:29:29 GMT',
//      'content-type': 'application/json',
//      'transfer-encoding': 'chunked',
//      connection: 'close',
//      'set-cookie': [Object],
//      allow: 'GET, HEAD, OPTIONS',
//      vary: 'Accept, Cookie',
//      etag: '"8e269e3d041a747f3285f979c736d6ca"',
//      'x-frame-options': 'SAMEORIGIN',
//      via: '1.1 vegur',
//      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
//      server: 'cloudflare',
//      'cf-ray': '4ab80d7a6b16a08e-SLC' },
//   config: 
//    { adapter: [Function: httpAdapter],
//      transformRequest: [Object],
//      transformResponse: [Object],
//      timeout: 0,
//      xsrfCookieName: 'XSRF-TOKEN',
//      xsrfHeaderName: 'X-XSRF-TOKEN',
//      maxContentLength: -1,
//      validateStatus: [Function: validateStatus],
//      headers: [Object],
//      method: 'get',
//      url: 'https://swapi.co/api/people/9/',
//      data: undefined },
//   request: 
//    ClientRequest {
//      domain: null,
//      _events: [Object],
//      _eventsCount: 6,
//      _maxListeners: undefined,
//      output: [],
//      outputEncodings: [],
//      outputCallbacks: [],
//      outputSize: 0,
//      writable: true,
//      _last: true,
//      upgrading: false,
//      chunkedEncoding: false,
//      shouldKeepAlive: false,
//      useChunkedEncodingByDefault: false,
//      sendDate: false,
//      _removedHeader: {},
//      _contentLength: 0,
//      _hasBody: true,
//      _trailer: '',
//      finished: true,
//      _headerSent: true,
//      socket: [Object],
//      connection: [Object],
//      _header: 'GET /api/people/9/ HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: swapi.co\r\nConnection: close\r\n\r\n',
//      _headers: [Object],
//      _headerNames: [Object],
//      _onPendingData: null,
//      agent: [Object],
//      socketPath: undefined,
//      timeout: undefined,
//      method: 'GET',
//      path: '/api/people/9/',
//      _ended: true,
//      _redirectable: [Object],
//      parser: null,
//      res: [Object] },
//   data: 
//    { name: 'Biggs Darklighter',
//      height: '183',
//      mass: '84',
//      hair_color: 'black',
//      skin_color: 'light',
//      eye_color: 'brown',
//      birth_year: '24BBY',
//      gender: 'male',
//      homeworld: 'https://swapi.co/api/planets/1/',
//      films: [Object],
//      species: [Object],
//      vehicles: [],
//      starships: [Object],
//      created: '2014-12-10T15:59:50.509000Z',
//      edited: '2014-12-20T21:17:50.323000Z',
//      url: 'https://swapi.co/api/people/9/' } },
// { status: 200,
//   statusText: 'OK',
//   headers: 
//    { date: 'Tue, 19 Feb 2019 10:29:29 GMT',
//      'content-type': 'application/json',
//      'transfer-encoding': 'chunked',
//      connection: 'close',
//      'set-cookie': [Object],
//      allow: 'GET, HEAD, OPTIONS',
//      vary: 'Accept, Cookie',
//      etag: '"1533461f73c77c0311bd19cee2cedfc3"',
//      'x-frame-options': 'SAMEORIGIN',
//      via: '1.1 vegur',
//      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
//      server: 'cloudflare',
//      'cf-ray': '4ab80d7a6d99a034-SLC' },
//   config: 
//    { adapter: [Function: httpAdapter],
//      transformRequest: [Object],
//      transformResponse: [Object],
//      timeout: 0,
//      xsrfCookieName: 'XSRF-TOKEN',
//      xsrfHeaderName: 'X-XSRF-TOKEN',
//      maxContentLength: -1,
//      validateStatus: [Function: validateStatus],
//      headers: [Object],
//      method: 'get',
//      url: 'https://swapi.co/api/people/11/',
//      data: undefined },
//   request: 
//    ClientRequest {
//      domain: null,
//      _events: [Object],
//      _eventsCount: 6,
//      _maxListeners: undefined,
//      output: [],
//      outputEncodings: [],
//      outputCallbacks: [],
//      outputSize: 0,
//      writable: true,
//      _last: true,
//      upgrading: false,
//      chunkedEncoding: false,
//      shouldKeepAlive: false,
//      useChunkedEncodingByDefault: false,
//      sendDate: false,
//      _removedHeader: {},
//      _contentLength: 0,
//      _hasBody: true,
//      _trailer: '',
//      finished: true,
//      _headerSent: true,
//      socket: [Object],
//      connection: [Object],
//      _header: 'GET /api/people/11/ HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: swapi.co\r\nConnection: close\r\n\r\n',
//      _headers: [Object],
//      _headerNames: [Object],
//      _onPendingData: null,
//      agent: [Object],
//      socketPath: undefined,
//      timeout: undefined,
//      method: 'GET',
//      path: '/api/people/11/',
//      _ended: true,
//      _redirectable: [Object],
//      parser: null,
//      res: [Object] },
//   data: 
//    { name: 'Anakin Skywalker',
//      height: '188',
//      mass: '84',
//      hair_color: 'blond',
//      skin_color: 'fair',
//      eye_color: 'blue',
//      birth_year: '41.9BBY',
//      gender: 'male',
//      homeworld: 'https://swapi.co/api/planets/1/',
//      films: [Object],
//      species: [Object],
//      vehicles: [Object],
//      starships: [Object],
//      created: '2014-12-10T16:20:44.310000Z',
//      edited: '2014-12-20T21:17:50.327000Z',
//      url: 'https://swapi.co/api/people/11/' } },
// { status: 200,
//   statusText: 'OK',
//   headers: 
//    { date: 'Tue, 19 Feb 2019 10:29:29 GMT',
//      'content-type': 'application/json',
//      'transfer-encoding': 'chunked',
//      connection: 'close',
//      'set-cookie': [Object],
//      allow: 'GET, HEAD, OPTIONS',
//      vary: 'Accept, Cookie',
//      etag: '"a042f48465342e258a43f56321ccf2d6"',
//      'x-frame-options': 'SAMEORIGIN',
//      via: '1.1 vegur',
//      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
//      server: 'cloudflare',
//      'cf-ray': '4ab80d7a6d19a070-SLC' },
//   config: 
//    { adapter: [Function: httpAdapter],
//      transformRequest: [Object],
//      transformResponse: [Object],
//      timeout: 0,
//      xsrfCookieName: 'XSRF-TOKEN',
//      xsrfHeaderName: 'X-XSRF-TOKEN',
//      maxContentLength: -1,
//      validateStatus: [Function: validateStatus],
//      headers: [Object],
//      method: 'get',
//      url: 'https://swapi.co/api/people/43/',
//      data: undefined },
//   request: 
//    ClientRequest {
//      domain: null,
//      _events: [Object],
//      _eventsCount: 6,
//      _maxListeners: undefined,
//      output: [],
//      outputEncodings: [],
//      outputCallbacks: [],
//      outputSize: 0,
//      writable: true,
//      _last: true,
//      upgrading: false,
//      chunkedEncoding: false,
//      shouldKeepAlive: false,
//      useChunkedEncodingByDefault: false,
//      sendDate: false,
//      _removedHeader: {},
//      _contentLength: 0,
//      _hasBody: true,
//      _trailer: '',
//      finished: true,
//      _headerSent: true,
//      socket: [Object],
//      connection: [Object],
//      _header: 'GET /api/people/43/ HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: swapi.co\r\nConnection: close\r\n\r\n',
//      _headers: [Object],
//      _headerNames: [Object],
//      _onPendingData: null,
//      agent: [Object],
//      socketPath: undefined,
//      timeout: undefined,
//      method: 'GET',
//      path: '/api/people/43/',
//      _ended: true,
//      _redirectable: [Object],
//      parser: null,
//      res: [Object] },
//   data: 
//    { name: 'Shmi Skywalker',
//      height: '163',
//      mass: 'unknown',
//      hair_color: 'black',
//      skin_color: 'fair',
//      eye_color: 'brown',
//      birth_year: '72BBY',
//      gender: 'female',
//      homeworld: 'https://swapi.co/api/planets/1/',
//      films: [Object],
//      species: [Object],
//      vehicles: [],
//      starships: [],
//      created: '2014-12-19T17:57:41.191000Z',
//      edited: '2014-12-20T21:17:50.401000Z',
//      url: 'https://swapi.co/api/people/43/' } },
// { status: 200,
//   statusText: 'OK',
//   headers: 
//    { date: 'Tue, 19 Feb 2019 10:29:29 GMT',
//      'content-type': 'application/json',
//      'transfer-encoding': 'chunked',
//      connection: 'close',
//      'set-cookie': [Object],
//      allow: 'GET, HEAD, OPTIONS',
//      vary: 'Accept, Cookie',
//      etag: '"ecac854ae87fecc534b65c41c2f359c3"',
//      'x-frame-options': 'SAMEORIGIN',
//      via: '1.1 vegur',
//      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
//      server: 'cloudflare',
//      'cf-ray': '4ab80d7a6b44a088-SLC' },
//   config: 
//    { adapter: [Function: httpAdapter],
//      transformRequest: [Object],
//      transformResponse: [Object],
//      timeout: 0,
//      xsrfCookieName: 'XSRF-TOKEN',
//      xsrfHeaderName: 'X-XSRF-TOKEN',
//      maxContentLength: -1,
//      validateStatus: [Function: validateStatus],
//      headers: [Object],
//      method: 'get',
//      url: 'https://swapi.co/api/people/62/',
//      data: undefined },
//   request: 
//    ClientRequest {
//      domain: null,
//      _events: [Object],
//      _eventsCount: 6,
//      _maxListeners: undefined,
//      output: [],
//      outputEncodings: [],
//      outputCallbacks: [],
//      outputSize: 0,
//      writable: true,
//      _last: true,
//      upgrading: false,
//      chunkedEncoding: false,
//      shouldKeepAlive: false,
//      useChunkedEncodingByDefault: false,
//      sendDate: false,
//      _removedHeader: {},
//      _contentLength: 0,
//      _hasBody: true,
//      _trailer: '',
//      finished: true,
//      _headerSent: true,
//      socket: [Object],
//      connection: [Object],
//      _header: 'GET /api/people/62/ HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: swapi.co\r\nConnection: close\r\n\r\n',
//      _headers: [Object],
//      _headerNames: [Object],
//      _onPendingData: null,
//      agent: [Object],
//      socketPath: undefined,
//      timeout: undefined,
//      method: 'GET',
//      path: '/api/people/62/',
//      _ended: true,
//      _redirectable: [Object],
//      parser: null,
//      res: [Object] },
//   data: 
//    { name: 'Cliegg Lars',
//      height: '183',
//      mass: 'unknown',
//      hair_color: 'brown',
//      skin_color: 'fair',
//      eye_color: 'blue',
//      birth_year: '82BBY',
//      gender: 'male',
//      homeworld: 'https://swapi.co/api/planets/1/',
//      films: [Object],
//      species: [Object],
//      vehicles: [],
//      starships: [],
//      created: '2014-12-20T15:59:03.958000Z',
//      edited: '2014-12-20T21:17:50.451000Z',
//      url: 'https://swapi.co/api/people/62/' } } ]